language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - python setup.py install
  - pip install -r dev_requirements.txt

script: nosetests --with-coverage --cover-package=machotools machotools

notifications:
  email:
    recipients:
      - davidc@enthought.com
    on_success: change
    on_failure: always
